serial_number="TE5241599"
model_number="IBR300310-2NA041WW-0000"
private_label="Default"
hardware_revision="Undefined"
rated_power_mB=40
rf_range="30000 to 31000 MHz"
rf_freq_band="KaBand2"
lo_ID=0
lo_freq="29000 MHz"
lo_spectral_inversion="Non-Inverted"
if_range="1000 to 2000 MHz"
total_sys_hours=3935
internal_10MHz=1
supply_voltage_min=0
supply_voltage_max=0
