version=1
user_title="Undefined"
simulate=0
suppress=0
major_mask=511
minor_mask=0
suppress_mask=15
stat_log_time=1440
time_zone_offset=0
switching_mode=0
wg_sw1_pos1=1
wg_sw1_pos2=0
wg_sw2_pos1=0
wg_sw2_pos2=1
IFL_A_to_spare=0
IFL_B_to_spare=1
attenuation_A_to_Spare_mBm=0
attenuation_B_to_Spare_mBm=0
tenMHz_source=0
tenMHz_trim_A=0
tenMHz_trim_B=0
ip_addr="10.10.12.51"
mask="255.255.0.0"
gateway="10.10.10.1"
