/* This file generated by MIB Data Editor v1.07 */

#define	sysDescr0	12
#define	sysObjectID0	39
#define	sysContact0	81
#define	sysName0	104
#define	sysLocation0	125
#define	sysServices0	148
#define	ifNumber0	161
#define	enterprises0	172
#define	snmpTrapOID0	189
