/* This file generated by MIB Data Editor v1.07 */

#define	sysDescr_OID0   0
#define	sysObjectID_OID0   27
#define	sysUpTime_OID0   46
#define	sysContact_OID0   69
#define	sysName_OID0   92
#define	sysLocation_OID0   113
#define	sysServices_OID0   136
#define	ifNumber_OID0   149
#define	enterprises_OID0   162
#define	snmpTrapOID_OID0   175
