/* This file generated by MIB Data Editor v1.07 */

#define	sysDescr0_Length 15
#define	sysObjectID0_Length 7
#define	sysUpTime0_Length 4
#define	sysContact0_Length 11
#define	sysName0_Length 9
#define	sysLocation0_Length 11
#define	sysServices0_Length 1
#define	ifNumber0_Length 1
#define	enterprises0_Length 3
#define	snmpTrapOID0_Length 7
