CXXFLAGS =	-O2 -g -Wall -fmessage-length=0

OBJS =		Patient.o Virus.o simulation.o

LIBS =

TARGET =	simulation

$(TARGET):	$(OBJS)
	$(CXX) -o $(TARGET) $(OBJS) $(LIBS)

all:	$(TARGET)

clean:
	rm -f $(OBJS) $(TARGET)
