#ifndef MICRONET_My_webpages
#define MICRONET_My_webpages	1

/* put #includes for web pages here */
#include "index.h"
//#include "iServer_logo.h"
#include "eit_style.h"
#include "left_panel.h"
#include "logo.h"
//#include "h_overview.h"
#include "terminal.h"
#include "iport.h"
#include "overview.h"
#include "network.h"
#include "admin.h"
//#include "h_network.h"
#include "serial.h"
#include "multihost.h"
#include "packing.h"
#include "bridge.h"
#include "security.h"
#include "s_admin.h"
#include "device_setup.h"
#include "device_query.h"
#include "frame_02.h"
#include "system_admin.h"
#include "reboot.h"
#include "defaults.h"
#include "upgrade.h"
#include "diagnostics.h"
#include "iopins.h"
#include "change_login.h"
#include "change_admin.h"
#include "change_serial.h"
#include "setdeviceparam.h"
#include "read_device.h"
#include "alarm1.h"
#include "alarm2.h"
#include "alarm3.h"
#include "alarm4.h"
#include "alarm5.h"
#include "snmp_email.h"
#include "dis.h"
#include "t1.h"
#include "t_wait.h"
//#include "h_device_query.h"
//#include "h_device_setup.h"
//#include "h_diagnostics.h"
//#include "h_iopins.h"
//#include "h_read_device.h"
//#include "h_security.h"
//#include "h_serial.h"
//#include "h_snmp_email.h"
//#include "h_system.h"
//#include "h_terminal.h"
#include "grey.h"
#include "green.h"
#include "white.h"
//#include "help.h"
#include "host_active.h"
#include "host_down.h"
#include "rebooting.h"

void webpages_init(void);
void main_func(PSOCKET_INFO socket_ptr) cmx_reentrant;

#endif
