Documentaition related to the project.

How does one interpret the code size displayed in the output window. For example my program compiled for the LPC2368:

Program Size: Code=1264 RO-data=16 RW-data=0 ZI-data=1384

1. ZI Data: Zero Initialized Data

2. RO Data are the constants.
Total RAM Size = RW Data + ZI Data
Total ROM Size = Code + RO Data + RW Data

3. Some constants (RO data) are generated by the compiler/linker and might also be from libraries. So they will exist regardless that your program doesn't explicitly defines any constants.

Initially as of Oct 2007: 
--------------------------
RAM = 15748 + 180 =  16KB

ROM = 43664 + 14284 + 180 = 57KB

