/* This file generated by MIB Data Editor v1.07 */

#define	sysDescr_OID0   0
#define	sysObjectID_OID0   29
#define	sysUpTime_OID0   48
#define	sysContact_OID0   71
#define	sysName_OID0   94
#define	sysLocation_OID0   115
#define	sysServices_OID0   138
#define	ifNumber_OID0   151
#define	enterprises_OID0   164
#define	snmpTrapOID_OID0   177
