SRC1=bits_swap_variables_01
SRC2=bits_xor_ex_01
SRC3=bits_reverse_01
SRC4=bits_count_lookup_table_01
SRC5=bits_reverse_02

all: 
	gcc -g -Wall ${SRC1}.c -o ${SRC1}
	gcc -g -Wall ${SRC2}.c -o ${SRC2}
	gcc -g -Wall ${SRC3}.c -o ${SRC3}
	gcc -g -Wall ${SRC4}.c -o ${SRC4}
	gcc -g -Wall ${SRC5}.c -o ${SRC5}

clean:
	rm  ${SRC1} ${SRC2} ${SRC3} ${SRC4} ${SRC5}
	